# server port set
server:
  port: 8888

spring:
  application:
    name: config-service
  # rabbitmq set
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # profile information set
#  profiles:
#    active: native
  cloud:
    config:
      server:
        # native file 경로, git hub 에서 데이터를 가져오기 위해서 주석 처리
#        native:
#          search-locations: file://${user.home}/Documents/spring-cloud-mvn/native-file-repo
        # file protocol 을 이용해 불러 오려는 파일의 경로 지정
        git:
          # remote git repository
          uri: https://github.com/Lee-HyunSoo/spring-cloud-config
          # 이 때 remote git repository 를 private repository 로 생성 했을 경우, username 과 password 도 필요
#          username:
#          password:
          # local git repository
#          uri: file://Users/lhs/Documents/spring-cloud-mvn/git-lal-repo

# actuator set
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
